### ISSUE TITLE
DEMO's off-site notification not working?

### ISSUE THREAD

**Issue by scharinger** [mkalygin/fcm-demo#2]
Hi! I tried the demo page of yours. The on-site notification did work fine, but with the off-site there was not much going on. What is supposed to happen and does it work for you right now? 

I want to make sure the messaging works off-site before I try to implement on my.

Thank you for your time and help!

Best regards

**Comment by mkalygin** [comment]
Hello @scharinger,

I've tested the demo right now and it works for me. I use Node.js `v8.1.2`. I've updated the project so that it doesn't use harmony flag anymore.

The off-site notification is supposed to show you a browser notification shortly after a redirect to Google page. See screenshot:
![image](https://user-images.githubusercontent.com/1662910/33531097-11f22d24-d889-11e7-84fb-1bf8788838f4.png)

Make sure that you have all your API keys right. You need to use Server Key from your Firebase Cloud Messaging console and API Key for web apps from Firebase Console.

The Server Key has to be set in `FCM_SERVER_KEY` environment variable (you can use `.env` file for that).

The API Key is used on the client side in `public/app.js`.

**Comment by MarbilleJuntado** [comment]
@mkalygin Why does it need to redirected to another site for the push notification to appear? I tried removing the "window.location" part to see if it's gonna behave the same way, but it's only displaying a blue toastr.

**Comment by mkalygin** [comment]
@MarbilleJuntado because this is a notification, which is shown when the page is closed. Whenever you subscribe for push notifications on a website, it sends you notifications even if you are not on the website at that moment.
